server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_feed
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    show-sql: true



  mvc:
    static-path-pattern: /static/**

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: mailspring794@gmail.com
    password: vwwuxkuqqzblyfbz

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    test-connection: false
    protocol: smtp


  thymeleaf:
    prefix: classpath:/templates/
    enabled: true


